feat: add support to import custom ldif
JanssenProject/jans pull request #1002
Opened 2022-03-09 15:45 UTC by iromli

### Description

- Target issue: #891

### Implementation Details

1. the entrypoint will scan for all `.ldif` files under predefined directory `/app/custom_ldif` (where users can mount files into this directory)
1. for every `.ldif` file found, entrypoint will try to generate rendered template (if file contains template context) under `/app/tmp/`
1. entrypoint will import data parsed from the generated template into user-selected persistence (`ldap`/`sql`/`spanner`/`couchbase`)

2022-03-10 16:19 UTC, moabu requested changes
we need to add a how to to our docs section. I'll add that.

2022-03-10 16:19 UTC, moabu commented on docker-jans-persistence-loader/scripts/couchbase_setup.py
> +    def import_builtin_ldif(self, bucket_mappings, ctx):
What happens if the custom ldifs loaded override the builtin ldifs ?

2022-03-10 16:43 UTC, iromli commented on docker-jans-persistence-loader/scripts/couchbase_setup.py
> +    def import_builtin_ldif(self, bucket_mappings, ctx):
same behavior with builtin ldif files; data imported into persistence only if not exist

2022-03-11 12:24 UTC, moabu commented on docker-jans-persistence-loader/scripts/couchbase_setup.py
> +    def import_builtin_ldif(self, bucket_mappings, ctx):
ok we can improve in operations where the same item might be modified. Like modifying the builtin ldifs in one `key` such as adding a scope to a client.
We can leave this for a separate enhancement.

2022-03-11 12:25 UTC, moabu approved these changes

2022-03-11 12:25 UTC, merged