feat: support regex client attribute to validate redirect uris
JanssenProject/jans pull request #1005
Opened 2022-03-10 03:45 UTC by Milton-Ch

### Description

- Target issue #
https://github.com/JanssenProject/jans/issues/348

- Implementation Details
1. Added client attribute to validate redirect uris using a regex.
2. Added feature flag `redirectUrisRegexEnabled`.

2022-03-10 14:11 UTC, yuriyz requested changes
Looks good. Some minor feedback in inlined comments.

2022-03-10 14:11 UTC, yuriyz commented on jans-auth-server/server/src/main/java/io/jans/as/server/service/RedirectionUriService.java
> +                return redirectionUri.matches(client.getAttributes().getRedirectUrisRegex()) ? redirectionUri : null;
Yes, we definitely has to print in log why we rejected call. Also if you can log other places where it is rejected it will be helpful.

2022-03-10 14:11 UTC, yuriyz commented on jans-auth-server/server/src/test/java/io/jans/as/server/service/RedirectionUriServiceTest.java
> +    public void validateRedirectionUri() throws Exception {
I vote for X_Y_Z convention for test names, so it is clear X-what we test, Y - under what condition, Z - what we expect. Exactly same convention we discussed some time ago.

`validateRedirectionUri_withValidRedirectUri_shouldReturnNotNullValue`

2022-03-11 09:29 UTC, yuriyz approved these changes

2022-03-11 11:55 UTC, moabu approved these changes

2022-03-11 11:58 UTC, mbaser approved these changes

2022-03-11 11:58 UTC, merged

2022-03-11 12:45 UTC, pujavs reviewed
Approved