fix(jans-casa): primary button not changing color when customized via custom branding plugin
JanssenProject/jans pull request #10084
Opened 2024-11-07 18:17 UTC by mjatin-dev

closes #10053

2024-11-07 18:47 UTC, jgomer2001 requested changes
Please remove z-button from `tertiaryButton`

Also, if `btn` was removed from primary and third, is there some reason for `secondaryButton` to have it ?

2024-11-08 18:23 UTC, mjatin-dev commented
> z-button
I removed the z-button and also remove btn from secondary-button.

2024-11-08 18:52 UTC, jgomer2001 approved these changes

2024-11-09 09:37 UTC, duttarnab approved these changes

2024-11-11 07:10 UTC, maduvena approved these changes

2024-11-11 09:47 UTC, merged