fix(actions): microk8s action passing correct arguments
JanssenProject/jans pull request #10363
Opened 2024-12-06 20:24 UTC by misba7

closes #10353

2024-12-10 15:29 UTC, iromli submitted a review, later dismissed

2024-12-10 19:13 UTC, iromli submitted a review, later dismissed

2024-12-11 08:06 UTC, moabu requested changes

2024-12-11 08:06 UTC, moabu commented on .github/workflows/test-microk8s.yml
> +          JANS_VERSION=${JANS_VERSION:-"0.0.0-nightly"} # set JANS_VERSION to 0.0.0-nightly if not set.
remove comment please

2024-12-11 10:38 UTC, merged