fix(docs): refresh agama lab quick start guide with respect to the latest Agama Lab version
JanssenProject/jans pull request #10426
Opened 2024-12-16 10:45 UTC by ossdhaval

### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

#### Target issue
  
  
  
  
closes #issue-number-here

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [ ] **I confirm that there is no impact on the docs due to the code changes in this PR.**

2024-12-16 16:55 UTC, SafinWasi requested changes
Needs changes, lots of links point to private assets.

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +- You will need a GitHub account where Agama Lab GitHub app has been [integrated](https://github.com/GluuFederation/private/wiki/Sign-Up---Sign-In#need-for-github-account). GitHub
This link is inaccessible outside Gluu team members, and there is no need to link to this article regardless.

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +will be used as [development repository](https://github.com/GluuFederation/private/wiki/Flow-Designer#development-repository) and [release repository](https://github.com/GluuFederation/private/wiki/F
Private links. These should probably be either copied to the public wiki or their own pages in the docs.

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +username-password based user authentication project. The will be similar to
```suggestion
username-password based user authentication project. This will be similar to 
```

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +3. After successful sign in, the [project dashboard](https://github.com/GluuFederation/private/wiki/Agama-Lab-Project-Dashboard)
Private link

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    This will open the project in the [project editor](https://github.com/GluuFederation/private/wiki/Project-Editor).
Private link

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    flow editor. Refer to [this](https://github.com/GluuFederation/private/wiki/Project-Editor#working-with-the-flow-editor) guide if you need to understand how
Private link

2024-12-16 16:55 UTC, SafinWasi commented on docs/assets/agamalab-flow-passwd-edit-assignment.png
The `string type` box should not be checked. This will cause the authResult variable to be set to `"{}"` which is not the same as `{}`

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    authService = Call io.jans.server.service.authenticationService#class
```suggestion
    authService = Call io.jans.server.service.AuthenticationService#class 
```

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    cdiUtil = Call io.jans.service.cdi.uti.CdUtil#bean authService
```suggestion
    cdiUtil = Call io.jans.service.cdi.util.CdiUtil#bean authService
```

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    authResult = "{}"
```suggestion
    authResult = {}
```

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +        authResult.uid = "creds.uername"
```suggestion
        authResult.uid = creds.username
```

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +              RRF "__________"
This is definitely wrong, we don't need to RRF anything if the authentication failed

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +        When
```suggestion
        When authResult.success is true
```

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +        Finish __________
```suggestion
        Finish it_oghyk
```

2024-12-16 16:55 UTC, SafinWasi commented on docs/assets/agamalab-flow-passwd-edit-assignment-uid.png
String type should not be checked

2024-12-16 16:55 UTC, SafinWasi commented on docs/assets/agamalab-flow-passwd-edit-cdiutil-instance.png
`creds.username` and `creds.password` should be separate arguments, not one argument separated by spaces. This can be done by typing `creds.username`, hitting Enter, then typing `creds.password`.
![image](https://github.com/user-attachments/assets/eaba4586-969c-4a5e-8973-fd568bf64ebb)

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +- Follow [these instructions]() to test using the Janssen Server
Blank link

2024-12-16 16:55 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +  ![image](../../../assets/successful-tarp-auth-screen.png)
Needs a newline before image, otherwise it breaks the formatting.
![image](https://github.com/user-attachments/assets/d4fbfb39-dbe9-459a-98b8-88876be5267d)

2024-12-27 10:56 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +will be used as [development repository](https://github.com/GluuFederation/private/wiki/Flow-Designer#development-repository) and [release repository](https://github.com/GluuFederation/private/wiki/F
Thanks for your comment. I have replaced the private link with public link.

2024-12-27 10:57 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +- You will need a GitHub account where Agama Lab GitHub app has been [integrated](https://github.com/GluuFederation/private/wiki/Sign-Up---Sign-In#need-for-github-account). GitHub
Thanks for your comment. I have replaced the private link with public link.

2024-12-27 10:59 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +username-password based user authentication project. The will be similar to
Thank you for the comment. I have updated this content.

2024-12-27 10:59 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    This will open the project in the [project editor](https://github.com/GluuFederation/private/wiki/Project-Editor).
Thanks for your comment. I have replaced the private link with public link.

2024-12-27 11:00 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +3. After successful sign in, the [project dashboard](https://github.com/GluuFederation/private/wiki/Agama-Lab-Project-Dashboard)
Thanks for your comment. I have replaced the private link with public link.

2024-12-27 11:02 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +        Finish __________
Thank you for your comment. I have updated the code.

2024-12-27 11:03 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    flow editor. Refer to [this](https://github.com/GluuFederation/private/wiki/Project-Editor#working-with-the-flow-editor) guide if you need to understand how
Thanks for your comment. I have replaced the private link with public link.

2024-12-27 13:17 UTC, ossdhaval commented on docs/assets/agamalab-flow-passwd-edit-assignment-uid.png
Updated the setting.

2024-12-27 13:17 UTC, ossdhaval commented on docs/assets/agamalab-flow-passwd-edit-assignment.png
Updated the setting.

2024-12-27 13:19 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    authService = Call io.jans.server.service.authenticationService#class
Updated the code. Thanks.

2024-12-27 13:20 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    cdiUtil = Call io.jans.service.cdi.uti.CdUtil#bean authService
Updated the code. Thanks.

2024-12-27 13:21 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    authResult = "{}"
Updated the code. Thanks.

2024-12-27 13:21 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +        authResult.uid = "creds.uername"
Updated the code. Thanks.

2024-12-27 13:22 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +              RRF "__________"
Updated the code. Thanks.

2024-12-27 13:42 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +        When
Updated the code. Thanks.

2024-12-27 15:37 UTC, SafinWasi requested changes
Some errors are still not fixed.

2024-12-27 15:37 UTC, SafinWasi commented on docs/assets/agamalab-flow-passwd-edit-cdiutil-instance.png
The arguments here are still wrong. https://github.com/JanssenProject/jans/pull/10426#discussion_r1887159714

2024-12-27 15:37 UTC, SafinWasi commented on docs/assets/agamalab-flow-passwd-edit-assignment-uid.png
"String type" should be unchecked

2024-12-27 15:37 UTC, SafinWasi commented on docs/assets/agamalab-flow-passwd-edit-fail-finish.png
I don't think this is correct. The option selected should be "Flow finished with an error" with a description. Like so:
![image](https://github.com/user-attachments/assets/b6e86d8c-71af-4ada-a0cc-cb78515e33c5)

"Flow finished with a variable" is used when you want to return a predefined variable. "false" is not a variable. Technically `Finish false` is correct according to Agama syntax, but it is better to use descriptive option

2024-12-27 15:37 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    authResult = "{}"
This is still incorrect

2024-12-27 15:37 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +        authResult.uid = "creds.username"
```suggestion
        authResult.uid = creds.username
```

2024-12-27 15:37 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +        When authResult.uid is true
```suggestion
        When authResult.success is true
```

2024-12-27 15:37 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +- Follow [these instructions]() to test using the Janssen Server
Still blank link

2024-12-27 15:37 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +At this point we have all the components of an Agama project ready, and they are
As the screenshot shows, all Agama stuff should be on the main branch to create a release. So there should be instructions added to make a PR from `agama-lab-policy-designer` branch to default branch.

2024-12-27 15:37 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +  ![image](../../../assets/successful-tarp-auth-screen.png)
This still  looks wrong

2025-01-16 07:49 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +- Follow [these instructions]() to test using the Janssen Server
The blank link will point to a document that describes how to use the `deploy and test` feature of the Agama Lab. Riza is working on that document. I have added a note as a placeholder for now.

2025-01-16 07:51 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +  ![image](../../../assets/successful-tarp-auth-screen.png)
Document updated to fix this. Thank you for your comment.

2025-01-16 08:08 UTC, ossdhaval commented on docs/assets/agamalab-flow-passwd-edit-assignment-uid.png
Updated the document with new image. Thank you for your comment.

2025-01-16 08:40 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +At this point we have all the components of an Agama project ready, and they are
I think this section should be about `publishing` rather than `releasing` because project is being built for the first time. Your concern will be taken care as well.

2025-01-24 11:13 UTC, ossdhaval commented on docs/assets/agamalab-flow-passwd-edit-cdiutil-instance.png
Updated the code to address this. Thank you for your comment.

2025-01-24 11:15 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +    authResult = "{}"
Pushed one more update for the same. Thank you for your comment.

2025-01-24 11:16 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +        When authResult.uid is true
Updated the code to address this. Thank you for your comment.

2025-01-24 11:20 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +At this point we have all the components of an Agama project ready, and they are
I have updated the section to address the comment.

2025-01-24 11:24 UTC, ossdhaval commented
> should be `io.jans.as.server.service.AuthenticationService`

Thank you for pointing this out. I tried many different things, not realising that this was the issue. :man_facepalming: :handshake: :smiley:

2025-01-24 11:26 UTC, ossdhaval commented on docs/assets/agamalab-flow-passwd-edit-fail-finish.png
Updated the code to fix this.

2025-01-24 11:26 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +        authResult.uid = "creds.username"
Updated the code to address this. Thank you for your comment.

2025-01-27 12:11 UTC, jgomer2001 submitted a review, later dismissed

2025-01-27 12:11 UTC, jgomer2001 commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
Still referencing `PasswordService`

> create new authentication service instance

Inaccurate. It's just getting a class reference, not an instance

> `assign result to`: `authService`

should be `authServiceRef` or better, `authServiceClass`

> `assign result to`: `cdiUtilRef`

should be `authService`

If it's unclear why, ping me

2025-01-29 07:10 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +        authResult.uid = "creds.uername"
Hi @SafinWasi 

**A question**: 
The sole purpose of this assignment is to aid when showing the user name on the user interface during the retry. At least that is what I understood from the code. But when I see the UI HTML, it doesn't have any code that uses `authResult.uid`. And during testing as well, I don't see the username displayed during the retries. So, this assignment is not required. Owing to this, I have removed this assignment from the latest version of the flow in the quick start guide. It simplifies the flow. Is this ok?

2025-01-29 07:17 UTC, ossdhaval commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +- Follow [these instructions]() to test using the Janssen Server
Please ignore my previous comment. I have put in a link now that points to `how to test using Tarp`.

The doc that referred to in the previous comment is going to be a different document.

2025-01-29 07:34 UTC, ossdhaval commented on docs/assets/agamalab-flow-passwd-edit-cdiutil-instance.png
Updated the document to fix this.

2025-01-29 11:57 UTC, jgomer2001 approved these changes

2025-01-29 15:52 UTC, SafinWasi requested changes
One small correction, everything else looks good to me.

2025-01-29 15:52 UTC, SafinWasi commented on docs/janssen-server/developer/agama/quick-start-using-agama-lab.md
> +Follow the instructions [here](https://docs.jans.io/head/janssen-server/install/)
```suggestion
Follow the instructions [here](https://docs.jans.io/vreplace-janssen-version/janssen-server/install/)
```

2025-01-30 15:16 UTC, SafinWasi approved these changes
Looks good to me

2025-02-03 08:06 UTC, ossdhaval commented
This PR has been replaced by a #10779 . This PR has all the discussions and comments but it couldn't be merged due to `unverified` commits.

2025-02-03 08:06 UTC, closed without merging