Jans auth server client registration language metadata
JanssenProject/jans pull request #1237
Opened 2022-04-20 22:36 UTC by qbert2k

### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

#### Target issue
https://github.com/JanssenProject/jans/issues/1057

#### Implementation Details
See https://github.com/JanssenProject/jans/issues/1057

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2022-04-21 09:16 UTC, yuriyz requested changes
Added some improvements proposals, please check.

2022-04-21 09:16 UTC, yuriyz commented on jans-orm/model/src/main/java/io/jans/orm/model/base/ClientMetadataValue.java
> +public class ClientMetadataValue implements Serializable {
What do you think about naming it `LocalizedString` ? In this way it is more generic and can be used in other places where we need localized string without concern.

2022-04-21 09:16 UTC, yuriyz commented on jans-orm/model/src/test/java/io/jans/orm/model/base/ClientMetadataValueTest.java
> +        assertEquals(clientMetadataValue.size(), 12);
We should check serialized data contains format which we expect.

2022-04-21 09:16 UTC, yuriyz commented on jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java
> +    private static void clientMetadataValueFromJson(
We need static generic method in `LocalizedString` (`ClientMetadataValue`), it can be used in many places.

```
private static void fromJson(JSONObject requestObject, String key, BiFunction<String, Locale, Void> function) {
    ...
}
```

2022-04-21 09:16 UTC, yuriyz commented on jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java
> +    }
ClientMetadataValue -> LocalizedString.
We can add method to `LocalizedString` and reuse it.
```
    public Map<String, String> addToMap(Map<String, String> map, String key) {
        if (!values.isEmpty) {
            return map;
        }

        for (String languageTag : getLanguageTags()) {
            if (StringUtils.isBlank(languageTag)) {
                map.put(key, getValue());
            } else {
                map.put(key + "#" + languageTag, getValue(languageTag));
            }
        }
        return map;
    }
```

2022-04-21 09:16 UTC, yuriyz commented on jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java
> +    private void addClientMetadataParam(JSONObject parameters, RegisterRequestParam registerRequestParam, ClientMetadataValue clientMetadataValue) {
If add `addToMap()` method then this I guess can be tricked as (pseudo code that has to be checked.): 

`new JSONObject(localicalizedString.addToMap(jsonObject.ToMap(), registerRequestParam.toString()));`

Advantage is that we can re-use `addToMap` in other places.

2022-05-12 03:51 UTC, qbert2k commented
Hi, @yuriyz
Regarding the sonar issues:

1. The dupplicated lines of code are between Client.java and RegisterRequest.java and because they are not related and I think hineritance is not a good solution. I am thinking to use Lombok, what do you think?
2. There is annother compilation issue bloking the merge request. A compilation issue in jans-client-api but it seems not related to the changes in jans-auth-server.

2022-05-12 08:00 UTC, yuriyz commented
Yes, I like lombok idea to reduce boilerplate code. Re: jans-client-api - ignore it. @jmunozherbas will correct it.

But if PR is ready we can let it go. Lets add lombok in separate PR. I don't want to put everything in one bucket. Duplicated lines is not end of the world. @qbert2k otherwise PR is ready, right ?

2022-05-12 21:21 UTC, yuriyz approved these changes

2022-05-12 21:22 UTC, merged