feat: add newly redesigned jans-client-api
JanssenProject/jans pull request #1540
Opened 2022-06-10 15:16 UTC by iromli

### Description

The changeset adds/updates several areas listed below:

* `jans-client-api` is updated
* added Jetty 11 to run `jans-client-api`
* added new env var `CN_CLIENT_API_CERT_CN` to gradually replace deprecated `CN_CLIENT_API_APPLICATION_CERT_CN` and `CN_CLIENT_API_ADMIN_CERT_CN`
* updated Helm charts

**Note:** the env var `CN_CLIENT_API_APPLICATION_CERT_CN` is used as backward-compat. An ideal upgrade involves removing the env var and use `CN_CLIENT_API_CERT_CN` instead.

2022-06-11 06:46 UTC, iromli commented
@moabu PR is ready for review.

2022-06-13 12:01 UTC, moabu requested changes

2022-06-13 12:01 UTC, moabu commented on automation/rancher-partner-charts/questions.yaml
>      label: Client API admin keystore name
This section can be removed. A deprecated note is not needed since this service was never in a working state.

2022-06-13 12:01 UTC, moabu commented on charts/janssen/charts/config/templates/configmaps.yaml
>    CN_CLIENT_API_ADMIN_CERT_CN: {{ .Values.configmap.cnClientApiAdminCertCn | quote }}
This section can be removed. A deprecated note is not needed since this service was never in a working state.

2022-06-13 12:01 UTC, moabu commented on charts/janssen/values.schema.json
> +            },
Remove

2022-06-13 12:01 UTC, moabu commented on docker-jans-client-api/README.md
> +- `CN_CLIENT_API_ADMIN_CERT_CN`: CommonName used in admin certificate subject. This environment variable is **DEPRECATED** and no longer used.
Remove

2022-06-13 12:01 UTC, moabu commented on docker-jans-client-api/README.md
> +    "script_log_level": "INFO"
add loggers spec to chart

2022-06-13 18:53 UTC, moabu approved these changes

2022-06-13 18:53 UTC, merged