fix: jans-cli README broken link
JanssenProject/jans pull request #1664
Opened 2022-07-04 11:30 UTC by devrimyatar

* Remove broken link
* Add Documentation section to point CLI docs

2022-07-04 11:47 UTC, moabu requested changes

2022-07-04 11:47 UTC, moabu commented on jans-cli/README.md
> +We have extensive documentation for CLI: [https://github.com/JanssenProject/jans/tree/main/docs/admin/jans-cli](https://github.com/JanssenProject/jans/tree/main/docs/admin/jans-cli)
replace with "Extensive documentation for the CLI can be found [here](https://github.com/JanssenProject/jans/tree/main/docs/admin/jans-cli)"

2022-07-04 11:47 UTC, moabu commented on jans-cli/README.md
> +So, That was a quick start to view how this _jans-cli_ Interactive Mode works. Please, see documentation for further information.
Replace with "The above was a quick start to how _jans-cli_ Interactive Mode works. Please, see documentation for further information."

2023-02-21 10:23 UTC, ossdhaval commented
Hi @devrimyatar 
This is a quick one. Merge it if it is still relevant, else close it.

2023-04-27 08:27 UTC, ossdhaval commented
Closing this PR as confirmed by @devrimyatar to be outdated.

2023-04-27 08:27 UTC, closed without merging