feat: jans-linux-setup Script for Keystroke Authentication
JanssenProject/jans pull request #1853
Opened 2022-07-22 13:39 UTC by devrimyatar

Feat: as described in https://github.com/GluuFederation/oxAuth/issues/1695

2022-07-22 13:39 UTC, mo-auto commented
Error: Hi @devrimyatar, You did not reference an open issue in your [PR](1853). I attempted to create an [issue](#1854) for you.    
 Please update that [issues'](#1854) title and body and make sure I correctly referenced it in the above PRs body.

2022-07-22 13:44 UTC, maduvena approved these changes

2022-07-22 13:54 UTC, moabu submitted a review, later dismissed

2022-07-22 15:21 UTC, moabu requested changes

2022-07-22 15:21 UTC, moabu commented on jans-linux-setup/jans_setup/templates/scripts.ldif
> +displayName: update_token_sample
Change display name to perhaps `scan_update_token` ?

2022-07-23 17:04 UTC, moabu approved these changes

2022-07-23 17:05 UTC, merged