feat(jans-auth-server):get up tests updating arquillian and jetty-embedded issue 1247
JanssenProject/jans pull request #2017
Opened 2022-08-04 04:37 UTC by jmunozherbas

### Prepare

- [X] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [X] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description
Updating arquillian version, to allow running embedded jetty tests.

#### Target issue
  https://github.com/JanssenProject/jans/issues/1247
closes #1247

#### Implementation Details
upgrade version arquillian-jetty-embedded-11   1.0.0.CR4
upgrade version arquillian test 1.7.0.Alpha10
allow using injection inside tests

-------------------
### Test and Document the changes
- [X] Static code analysis has been run locally and issues have been fixed
- [X] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2022-08-04 09:02 UTC, yuriyz requested changes

2022-08-04 09:02 UTC, yuriyz commented on jans-auth-server/server/src/test/java/io/jans/as/server/BaseComponentTest.java
> +        return (ClientService) HM_TEST_INJECTOR.get("ClientService");
Can you check whether `CdiUtil.bean(ClientService.class)` will work instead of alien static holder? If it will work we have to drop this map.

2022-08-04 22:00 UTC, jmunozherbas commented on jans-auth-server/server/src/test/java/io/jans/as/server/BaseComponentTest.java
> +        return (ClientService) HM_TEST_INJECTOR.get("ClientService");
I have applied CdiUtil.bean, it is working thanks.

2022-08-05 08:09 UTC, yuriyz approved these changes

2022-08-05 08:09 UTC, merged