fix(config-api): specifying JSON values for Attribute enum properties
JanssenProject/jans pull request #2663
Opened 2022-10-18 18:46 UTC by pujavs

### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description
Mismatch of enum case in auto generated swagger schema components and resteasy jackson serialized enum in response.

#### Target issue
  
  
  
  
closes #2645 

#### Implementation Details
  

To resolve this modified core models by annotating getter with @JsonValue for controlling the marshalling output for an enum values.

**Details of model changed:**
- `dataType` - AttributeDataType.java -> https://github.com/JanssenProject/jans/blob/jans-auth-server-client-registration-language-metadata-fix-tests/jans-core/model/src/main/java/io/jans/model/attribute/AttributeDataType.java
- `editType` & `viewType` - GluuUserRole.java -> https://github.com/JanssenProject/jans/blob/jans-auth-server-client-registration-language-metadata-fix-tests/jans-core/service/src/main/java/io/jans/model/GluuUserRole.java
- `usageType` - GluuAttributeUsageType.java -> https://github.com/JanssenProject/jans/blob/jans-auth-server-client-registration-language-metadata-fix-tests/jans-core/service/src/main/java/io/jans/model/GluuAttributeUsageType.java
`status` - GluuStatus.java -> https://github.com/JanssenProject/jans/blob/jans-auth-server-client-registration-language-metadata-fix-tests/jans-core/model/src/main/java/io/jans/model/GluuStatus.java

**Testing:** Before and after
![image](https://user-images.githubusercontent.com/43700552/196517578-f968dc3d-af16-437a-8f65-2b0dc366f568.png)

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2022-10-18 19:47 UTC, yuriyz requested changes
Problem is that if in any place where direct serialization is used (e.g. field marked `@JsonObject`) it will break deserialization. Because in previous version direct serialization will be uppercase and with this PR it will be lowercase -> `com.fasterxml.jackson.core.JsonParseException: Unrecognized token`.

Impact is too big. You can workaround it with custom deserializer to json creator, e.g.
```
public enum DataType {
    JSON("json"), 
    HTML("html");

    private String key;

    DataType(String key) {
        this.key = key;
    }

    @JsonCreator
    public static DataType fromString(String key) {
        return key == null
                ? null
                : DataType.valueOf(key.toUpperCase());
    }

    @JsonValue
    public String getKey() {
        return key;
    }
}
```
Why did we get this issue in first place? It sounds as it comes too far if it's about swagger generation.

2022-10-19 06:14 UTC, pujavs commented
because when manually creating swagger spec i had control in defining enums in uppercase but in auto generation swagger core generates it.

2022-10-19 14:00 UTC, pujavs commented
Resolved the requested change by using datatype-specific serialization - Jackson ObjectMapper

2022-10-19 14:06 UTC, yuriyz approved these changes

2022-10-19 14:07 UTC, merged