Update logs.md
JanssenProject/jans pull request #3780
Opened 2023-02-06 08:13 UTC by manojs1978

### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

#### Target issue
  
  
  
  
closes #issue-number-here

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2023-02-06 08:14 UTC, mo-auto approved these changes

2023-02-16 20:08 UTC, mo-auto submitted a review, later dismissed

2023-07-18 07:50 UTC, ossdhaval requested changes

2023-07-18 07:50 UTC, ossdhaval commented on docs/admin/scim/logs.md
> +   Generally it's convenient to set the logging level for both jans-Auth and SCIM to DEBUG.
`Generally it's convenient to set the logging level for both jans-Auth and SCIM to DEBUG.`

This statement is too broad. Either remove it or add link to where steps for enabling debug are listed. Other content look ok.

2023-07-18 07:50 UTC, ossdhaval commented on docs/admin/scim/logs.md
>  ## Have questions in the meantime?
Consider removing this section.

2023-07-18 08:19 UTC, manojs1978 commented on docs/admin/scim/logs.md
>  ## Have questions in the meantime?
made changes accordingly

2023-07-19 04:39 UTC, ossdhaval approved these changes

2023-10-23 07:48 UTC, closed without merging

2023-10-23 07:49 UTC, manojs1978 commented
very old updates , which are already updated