fix(jans-cli-tui): change help content for agama page
JanssenProject/jans pull request #4765
Opened 2023-05-01 13:22 UTC by AbdelwahabAdam

### Description
- Change help (<f1>) content in agam page.
#### Target issue
https://github.com/JanssenProject/jans/issues/4725
  
closes #4725

#### Implementation Details
  - it is generic now, and we can add custom help for any desired page.

2023-05-01 14:06 UTC, devrimyatar requested changes
Typo "Visite"  should be "Visit"

2023-05-01 14:13 UTC, AbdelwahabAdam commented
> Typo "Visite" should be "Visit"

fixed

2023-05-02 18:28 UTC, devrimyatar approved these changes

2023-05-02 20:18 UTC, yuriyz approved these changes

2023-05-02 20:18 UTC, merged