docs: vm upgrade using terraform
JanssenProject/jans pull request #5551
Opened 2023-07-14 08:06 UTC by misba7

### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

#### Target issue
  
  
  
  
closes #issue-number-here

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2023-07-14 08:07 UTC, mo-auto commented
Error: Hi @misba7, You did not reference an open issue in your [PR](5551). I attempted to create an [issue](#5552) for you.    
 Please update that [issues'](#5552) title and body and make sure I correctly referenced it in the above PRs body.

2023-07-17 09:54 UTC, moabu requested changes

2023-07-17 09:54 UTC, moabu commented on docs/admin/vm-ops/upgrade.md
> +Let's assume we are upgrading Jans VM installation from version `1.0.14` to `1.0.15`
rephrase the assumption to remove `1.0.14` . You can simply rephrase it to `current version` to `vreplace-janssen-version`

2023-07-17 09:54 UTC, moabu commented on docs/admin/vm-ops/upgrade.md
> +2. [Install](../install/vm-install/README.md) on a separate VM the target new Jans installation, i.e. 1.0.15.
replace all `1.0.15` with `vreplace-janssen-version`

2023-07-24 05:16 UTC, moabu approved these changes

2023-07-24 05:17 UTC, merged