feat: add dcr load test
JanssenProject/jans pull request #5566
Opened 2023-07-18 13:23 UTC by moabu

Adds dcr load testing to the container testing demo
  
closes #5438

2023-07-18 13:24 UTC, mo-auto commented
Error: Hi @moabu, You did not reference an open issue in your [PR](5566). I attempted to create an [issue](#5567) for you.    
 Please update that [issues'](#5567) title and body and make sure I correctly referenced it in the above PRs body.

2023-07-18 13:33 UTC, yuriyz submitted a review, later dismissed

2023-07-19 10:31 UTC, yuriyz approved these changes

2023-07-19 12:58 UTC, yuriyz requested changes

2023-07-19 12:58 UTC, yuriyz commented on demos/benchmarking/docker-jans-loadtesting-jmeter/scripts/tests/register_client.jmx
> +                <stringProp name="135960981">&quot;DCR_CLIENT_ID&quot;</stringProp>
Revert this change, we are asserting "client_id" presence

2023-07-19 13:37 UTC, yuriyz submitted a review, later dismissed

2023-07-19 15:26 UTC, merged