feat(jans-linux-setup): load test data to external Jans setup
JanssenProject/jans pull request #5661
Opened 2023-07-27 12:11 UTC by devrimyatar

closes #5625

You need to provide identifiers in templates as argument to script. For example to load template specified in issue,
```
python3 external_data_load.py -salt=v0j94qcGoCA9Y0MnpWfstIVa -db-type=mysql -rdbm-user=jansr -rdbm-password=qwerty -rdbm-db=jansdb -rdbm-host=test.jans.info -template=/opt/jans/jans-setup/templates/test/jans-auth/data/oxauth-test-data.ldif --hostname=test.jans.info --oxauthClient_4_inum=1800.29fb081b-fdee-4352-a192-4477ae285f6b oxauthClient_2_inum=HFf0vsdvKZ4k oxauthClient_4_encoded_pw="eUvI2v0SaERZgNRha/iqdw==" oxauthClient_2_encoded_pw="saaeUvI2v0SaERZgNRhaiq=" oxauthClient_3_inum=600.29fb081b-fdee-4352-a192-4477ae285f6b  oxauthClient_3_encoded_pw="G55is6yKNI4="
```

2023-07-31 05:32 UTC, moabu requested changes
Works. Thanks for this @devrimyatar . We need documentation so I will reassign this to @ossdhaval .

2023-07-31 14:46 UTC, yurem approved these changes

2023-12-30 14:15 UTC, jgomer2001 approved these changes

2024-01-01 10:01 UTC, moabu approved these changes

2024-01-01 10:02 UTC, merged