docs: fixes
JanssenProject/jans pull request #5984
Opened 2023-09-08 11:56 UTC by misba7

### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

#### Target issue
  
  
  
  
closes #issue-number-here

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2023-09-08 11:57 UTC, mo-auto commented
Error: Hi @misba7, You did not reference an open issue in your [PR](5984). I attempted to create an [issue](#5985) for you.    
 Please update that [issues'](#5985) title and body and make sure I correctly referenced it in the above PRs body.

2023-09-08 12:10 UTC, yuriyz approved these changes

2023-09-11 12:04 UTC, moabu requested changes

2023-09-11 12:04 UTC, moabu commented on docs/script-catalog/person_authentication/fido2-external-authenticator/README.md
> +![fido2](../../../assets/image_fido2.png)
Leave as is. The assets are generated.

2023-09-11 12:04 UTC, moabu commented on docs/script-catalog/person_authentication/fido2-external-authenticator/README.md
> +![fido2](../../../assets/image-fido2-ldap-structure.png)
Leave as is. The assets are generated

2023-09-17 15:43 UTC, moabu requested changes

2023-09-17 15:43 UTC, moabu commented on docs/script-catalog/person_authentication/fido2-external-authenticator/README.md
> +[FIDO2 interception script](https://github.com/JanssenProject/jans/blob/v1.0.16/docs/script-catalog/person_authentication/fido2-external-authenticator/Fido2ExternalAuthenticator.py)
You will break the auto doc generator and the docs will be outdated. Please do not remove the special keywords like `vreplace-janssen-version` with any specific version in head. This goes for there other locations in which this has occurred

2023-10-18 03:20 UTC, moabu requested changes

2023-10-18 03:20 UTC, moabu commented on docs/script-catalog/person_authentication/fido2-external-authenticator/README.md
> -The design is being rendered from the [FIDO2 xhtml page](https://github.com/JanssenProject/jans/blob/vreplace-janssen-version/jans-auth-server/server/src/main/webapp/auth/fido2/login.xhtml). To custo
Please use `vreplace-janssen-version` instead of head

2023-10-18 03:20 UTC, moabu commented on docs/admin/terraform/README.md
> +        1. client_id: `kubectl get cm cn -n <namespace>  --template={{.data.jca_client_id}}`
you can now use the `test_client_id` as thats working. You can add the jca as a fallback

2023-10-18 09:51 UTC, moabu approved these changes

2023-10-18 09:53 UTC, merged