docs: TUI install and connect to k8s installation
JanssenProject/jans pull request #5996
Opened 2023-09-10 19:29 UTC by misba7

### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

#### Target issue
  https://github.com/JanssenProject/jans/issues/5995
  
  
  
closes #issue-number-here

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2023-09-10 19:30 UTC, mo-auto commented
Error: Hi @misba7, You did not reference an open issue in your [PR](5996). I attempted to create an [issue](#5997) for you.    
 Please update that [issues'](#5997) title and body and make sure I correctly referenced it in the above PRs body.

2023-09-11 12:01 UTC, moabu requested changes

2023-09-11 12:01 UTC, moabu commented on docs/admin/kubernetes-ops/tui-k8s.md
> +    `wget https://github.com/JanssenProject/jans/releases/download/v1.0.17.nightly/jans-cli-tui-linux-ubuntu-X86-64.pyz`
Use `vreplace-janssen-version` instead of `v1.0.17.nightly` so it gets substituted automatically

2023-09-12 08:57 UTC, moabu commented
i'm adding a video to this doc . I'll merge right after.

2023-09-12 08:57 UTC, moabu approved these changes

2023-09-12 08:58 UTC, merged