feat(config-api, keycloak):  saml plugin to create trust client in DB and keycloak storage provider to jans store
JanssenProject/jans pull request #6155
Opened 2023-09-28 16:31 UTC by pujavs

### Prepare
 New config-api plugin to expose endpoints to create and manage trust relationships and persist in DB- issue#5148 
jans-keycloak-storage-api related changes
-------------------

### Description

#### Target issue
  
  
  
  
closes #5148 
          #6177 

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2023-09-28 17:12 UTC, moabu requested changes

2023-09-28 17:12 UTC, moabu commented on docs/admin/install/setup.md
> +<<<<<<< HEAD
watch out from merge operations. I can see this across your code.

2023-09-28 17:12 UTC, moabu commented on docs/admin/install/setup.md
> +>>>>>>> c49aae345dccea56c9b1af51f6d95ebc527201bf
like here

2023-09-28 17:12 UTC, moabu commented on docs/admin/install/setup.md
> +<<<<<<< HEAD
and here

2023-09-28 17:12 UTC, moabu commented on jans-config-api/plugins/keycloak-plugin/dependency-reduced-pom.xml
> +    <version>1.0.17-SNAPSHOT</version>
use 1.0.19-SNAPSHOT

2023-09-29 08:01 UTC, pujavs commented on docs/admin/install/setup.md
> +>>>>>>> c49aae345dccea56c9b1af51f6d95ebc527201bf
Fixed.

2023-09-29 08:01 UTC, pujavs commented on docs/admin/install/setup.md
> +<<<<<<< HEAD
Fixed.

2023-09-29 08:02 UTC, pujavs commented on jans-config-api/plugins/keycloak-plugin/dependency-reduced-pom.xml
> +    <version>1.0.17-SNAPSHOT</version>
Fixed.

2023-09-30 07:42 UTC, moabu submitted a review, later dismissed

2023-10-02 09:42 UTC, yuriyz approved these changes

2023-10-02 15:40 UTC, yurem approved these changes

2023-10-09 08:06 UTC, devrimyatar submitted a review, later dismissed

2023-10-09 11:11 UTC, yuriyz approved these changes

2023-10-10 11:24 UTC, moabu approved these changes

2023-10-10 15:20 UTC, moabu approved these changes

2023-10-10 15:21 UTC, merged