Issues 5330 review
JanssenProject/jans pull request #6157
Opened 2023-09-28 17:13 UTC by shekhar16

#5330

2023-09-29 17:12 UTC, yurem approved these changes

2023-09-29 17:16 UTC, yurem approved these changes

2023-10-05 16:57 UTC, yurem approved these changes

2023-10-05 20:37 UTC, yuriyz requested changes
Version has to be in sync with main otherwise it will be out of sync with other projects in mono repo. Current version is  1.0.19-SNAPSHOT.

2023-10-05 20:37 UTC, yuriyz commented on jans-keycloak-link/model/pom.xml
> +        <version>1.0.17-SNAPSHOT</version>
Current version is 1.0.19-SNAPSHOT

2023-10-05 20:37 UTC, yuriyz commented on jans-keycloak-link/pom.xml
> +  <version>1.0.17-SNAPSHOT</version>
Current version is 1.0.19-SNAPSHOT

2023-10-05 20:37 UTC, yuriyz commented on jans-keycloak-link/server/pom.xml
> +        <version>1.0.17-SNAPSHOT</version>
Current version is 1.0.19-SNAPSHOT

2023-10-05 20:37 UTC, yuriyz commented on jans-keycloak-link/server/weld-validation-report.html
> +<html><head><title>Weld - Validation Report</title><style>body {
What is the purpose of this file in the project ?

2023-10-05 20:37 UTC, yuriyz commented on jans-keycloak-link/service/pom.xml
> +        <version>1.0.17-SNAPSHOT</version>
Current version is 1.0.19-SNAPSHOT

2023-10-06 18:52 UTC, shekhar16 commented on jans-keycloak-link/service/pom.xml
> +        <version>1.0.17-SNAPSHOT</version>
All changes are done.

2023-10-07 20:08 UTC, yuriyz submitted a review, later dismissed

2023-10-10 17:15 UTC, yurem approved these changes

2023-10-10 17:17 UTC, yurem approved these changes

2023-10-10 19:08 UTC, yuriyz approved these changes

2023-10-11 05:56 UTC, merged