fix: brazilob jarm fapi conformance test last7 issues
JanssenProject/jans pull request #688
Opened 2022-01-24 12:44 UTC by HemantKMehta

properly formatted code fix for Brazil OB JARM fapi1-advanced-final issue (new numbers on monorepo)# 310 to 315

2022-01-24 13:01 UTC, yuriyz requested changes
Logic itself is good but code needs to be improved a bit. Please check inlined comments.

2022-01-24 13:01 UTC, yuriyz commented on jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java
> +        //assertNotNull(registerResponse.getClientSecretExpiresAt());
Normally expiration should be present, no ? At least for clients which we dynamically registered by tests.

2022-01-24 13:01 UTC, yuriyz commented on jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java
> +        //assertNotNull(registerResponse.getClientSecretExpiresAt());
same thing

2022-01-24 13:01 UTC, yuriyz commented on jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/jarm/AuthorizationResponseModeJwtResponseTypeCodeSignedEncryptedHttpTest.java
> +	    //RegisterResponse registerResponse = registerClient(redirectUris, responseTypes, sectorIdentifierUri, clientJwksUri,
Many new lines (55-56) as well as commented lines in this class. Lets remove unused code.

2022-01-24 13:01 UTC, yuriyz commented on jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/jarm/AuthorizationResponseModeJwtResponseTypeCodeSignedEncryptedHttpTest.java
> +	    //JwtAuthorizationRequest jweAuthorizationRequest = new JwtAuthorizationRequest(authorizationRequest,
Unused code and redundant new lines.

2022-01-24 13:01 UTC, yuriyz commented on jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/jarm/AuthorizationResponseModeJwtResponseTypeCodeSignedEncryptedHttpTest.java
> +	    //assertEquals(response.getClaims().getClaimAsString("error"), "invalid_request_object");
If you wish to assert error, simply add it to https://github.com/JanssenProject/jans/blob/546b1c23becbf9d00cdb4aaaeb086a44a9fb518b/jans-auth-server/client/src/test/java/io/jans/as/client/client/Asserter.java#L38

No need to keep commented lines.

2022-01-24 13:01 UTC, yuriyz commented on jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
> +					responseMode = extractResponseMode(request);
Would you please replace tabs with spaces? Then it does not look messed on github.

2022-01-24 13:01 UTC, yuriyz commented on jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
> +						fillRedirectUriResponseforJARM(redirectUriResponse, clientId, client);
1. Inside `fillRedirectUriResponseforJARM` method we are passing clientId and client objects. Client has that id already thus no need to pass `clientId` (`client.getClientId()`).
2. pass inside method Jwt object, and populate whatever is needed inside: 

```
private void fillRedirectUriResponseforJARM(redirectUriResponse, jwt, client) {
    JwtClaims jwtClaims = jwt.getClaims();
    String tempRedirectUri = jwtClaims.getClaimAsString("redirect_uri");
    if (tempRedirectUri != null) {
        redirectUriResponse.getRedirectUri().setBaseRedirectUri(URLDecoder.decode(tempRedirectUri, "UTF-8"));
    }
    redirectUriResponse.getRedirectUri().setResponseMode(ResponseMode.JWT);
    state = jwtClaims.getClaimAsString("state");
    if (state != null) {
        redirectUriResponse.setState(state);
    }
    ....
}
```

2022-01-24 13:01 UTC, yuriyz commented on jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
> +			redirectUriResponse.getRedirectUri().setIssuer(appConfiguration.getIssuer());
tabs->spaces

2022-01-24 13:01 UTC, yuriyz commented on jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java
> +		String redirectUri = jwtRequest.getRedirectUri();
tabs -> spaces

2022-01-25 06:56 UTC, HemantKMehta commented on jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java
> +        //assertNotNull(registerResponse.getClientSecretExpiresAt());
done

2022-01-25 09:09 UTC, closed without merging