feat: add support for custom scripts
JanssenProject/jans pull request #6970
Opened 2023-12-06 13:17 UTC by moabu

### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

#### Target issue
  
  
  
  
closes #6969 

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2023-12-06 18:51 UTC, iromli requested changes

2023-12-06 18:51 UTC, iromli commented on docs/admin/kubernetes-ops/customization.md
> +          subPath: mymycustomjar.sh
`subPath` should be `mycustom.jar`

2023-12-06 18:51 UTC, iromli commented on docs/admin/kubernetes-ops/customization.md
> +            name: my-custom-jar
May need to adjust `defaultMode` to add proper executable permission for the script. By default it's `420` (equivalent to `0644`).

2023-12-08 11:20 UTC, misba7 approved these changes

2023-12-08 11:29 UTC, merged