fix(kc-saml-plugin): fixed IDP creation issue, enum values and removed kc lib dependency
JanssenProject/jans pull request #7238
Opened 2024-01-02 16:19 UTC by pujavs

### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description
1) Issue#6514: feat(kc-saml-plugin): keycloak weld conflict with jans weld , remove keycloak dependency 
2) Issue#7200: fix(config-api): status response value of attributes
3) Issue#7190: fix(kc-saml-plugin): create IDP request error for individual metedata elements.
4) Issue#7192: fix(config-api): script type creation throwing error 

#### Target issue
  
  
  
  
closes #6514 7200 7190 7192

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2024-01-02 17:52 UTC, yurem approved these changes

2024-01-03 07:44 UTC, devrimyatar requested changes
Please ask @yurem about:

I guess in `jans-config-api-swagger.yaml` line 960, **"NULL"** should be **DISABLED**

2024-01-03 08:15 UTC, pujavs commented
> Please ask @yurem about:
> 
> I guess in `jans-config-api-swagger.yaml` line 9860, **"NULL"** should be **DISABLED**

@devrimyatar, please verify now

2024-01-03 10:15 UTC, yurem approved these changes

2024-01-03 13:48 UTC, yuriyz approved these changes

2024-01-03 16:18 UTC, devrimyatar approved these changes

2024-01-03 16:19 UTC, merged