docs(jans-cli): upload test agama project
JanssenProject/jans pull request #8033
Opened 2024-03-12 12:09 UTC by devrimyatar

closes #8032

2024-03-12 12:15 UTC, mo-auto approved these changes

2024-03-13 08:55 UTC, ossdhaval requested changes

2024-03-13 08:55 UTC, ossdhaval commented on docs/admin/config-guide/agama-configuration.md
> +Let's upload [a test project](https://github.com/JanssenProject/jans/blob/main/docs/assets/agama/test-project.zip)
Hi @devrimyatar this PR doesn't have a `test-project.zip`. Did you mean `journey.zip`? 

Also, use the relative URLs in the docs when possible. For example `../../assets/agama/test-project.zip`

2024-03-13 08:55 UTC, ossdhaval commented on docs/admin/config-guide/agama-configuration.md
> +Let's update configuration for this project with [sample project configuration](https://github.com/JanssenProject/jans/blob/main/docs/assets/agama/journey-configs.json):
Kindly use the relative URL.

2024-03-13 11:56 UTC, ossdhaval approved these changes

2024-03-13 18:31 UTC, moabu approved these changes

2024-03-13 18:31 UTC, merged