chore(jans-keycloak-integration): bump kc version to 24.0.0 #8315
JanssenProject/jans pull request #8316
Opened 2024-04-16 08:27 UTC by uprightech

2024-04-16 08:30 UTC, moabu requested changes
Maybe 24.0.2 so that we lock it across the project. Dependabot has a couple of PRs up requesting that version

2024-04-16 12:47 UTC, yurem submitted a review, later dismissed

2024-04-16 13:27 UTC, devrimyatar approved these changes

2024-04-16 13:29 UTC, uprightech commented
> Maybe 24.0.2 so that we lock it across the project. Dependabot has a couple of PRs up requesting that version

Agreed. Modified PR title to reflect this

2024-04-17 02:49 UTC, moabu approved these changes

2024-04-17 02:50 UTC, merged