fix(charts): Fix indentation for JAVA_OPTIONS in deployments.
JanssenProject/jans pull request #8416
Opened 2024-04-30 08:08 UTC by saernz

### Description

#### Target issue
Fixes #8415
  
Closes #8415

If someone else could test this fixes the issue that would be great. I've so far tested it for the config-api by manually editing my janssen charts folder with the change, which fixed the issue for me. I haven't tested any of the other deployments.

2024-04-30 08:13 UTC, moabu commented
Thank you @saernz ! We will review this PR.

2024-04-30 08:23 UTC, moabu commented
We would truly appreciate it if you can sign your commits and DCO basically use the `-s and -S` options in `git`. Thanks again @saernz

2024-04-30 22:48 UTC, saernz commented
Sorry, should be all good now. Was not too keen to use my email but I found out how github does it privately.

2024-05-01 17:13 UTC, misba7 requested changes

2024-05-01 17:13 UTC, misba7 commented on charts/janssen/charts/auth-server/templates/deployment.yml
2 more whitespaces needed in auth-server

2024-05-01 17:13 UTC, misba7 commented on charts/janssen/charts/fido2/templates/deployment.yml
2 more whitespaces needed in fido2

2024-05-01 17:13 UTC, misba7 commented on charts/janssen/charts/scim/templates/deployment.yml
2 more whitespaces needed in scim

2024-05-01 23:30 UTC, saernz commented on charts/janssen/charts/auth-server/templates/deployment.yml
Hi @misba7 I think you are technically correct, but something strange is going on with the indentations of the charts.

If you look at the actual raw source of the deployment chart on the line there is only 10 spaces of indentation, though the template is using an indent function value of 12.

If you actually download the chart with helm, unzip the templates and open them up, they actually have an indentation of 12 spaces, even though in the raw source the lines only had an indent of 10.

I've found out this is because the raw template in the source code does not indent the array of containers, though in the unzipped charts, there is an indentation of 2 spaces for the containers array. I think somewhere in the pipeline the charts formatting is being corrected, so even though those lines only have an indent of 10 in the raw source, when they make it into the released charts, they end up with a correct indentation of 12.

I'm not sure where this formatting is happening, though it probably needs to be fixed to minimize confusion. Once it is fixed, someone's probably going to have to fix all the indenting in the raw source files too.

2024-05-01 23:40 UTC, saernz commented on charts/janssen/charts/auth-server/templates/deployment.yml
Ah I forgot to add, you can see what's happening by running: 

`helm template janssen jans.io/janssen -s charts/config-api/templates/deployment.yaml --set config-api.usrEnvs.normal.CN_CONFIG_API_PLUGINS="scim" --debug`

if you have the jans.io repo added.

2024-05-07 03:50 UTC, saernz commented
I think as per my reasoning in the resolved requested change we should probably be able to move ahead with this now. I'm not sure if there is a way to run a test release for the helm charts to see what happens?

As per my comments in the requested change, I believe there is something in the helm chart release pipeline that fixes the indentation of the raw source files, so even though the JAVA_OPTIONS are only indented by 10 in the raw source, once they pass through that pipeline, they become indented by 12. This is because the parent array of containers is indented differently in the raw helm templates in GitHub from what comes out the other side in the released helm chart where it has +2 spaces for array items. You can unzip the released helm charts and compare the differences from there.

I think whatever is happening to cause that is probably better fixed in another issue, though for now this fix should at least maintain the status quo.

2024-05-11 09:34 UTC, iromli approved these changes

2024-05-11 13:01 UTC, moabu approved these changes
I think @saernz is right and I believe it's coming from a source that's using a windows computer 🫢

2024-05-11 23:10 UTC, misba7 approved these changes

2024-05-13 06:16 UTC, merged