feat(cedarling): initial implementation for cedarling
JanssenProject/jans pull request #8691
Opened 2024-06-10 16:04 UTC by sokorototo

### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

#### Target issue
  
  It doesn't close any issue, as this is new territory.

#### Implementation Details
  Initial implementation for `cedarling`

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2024-06-10 16:21 UTC, nynymike submitted a review, later dismissed
In the future we want smaller PR's.

2024-06-11 08:55 UTC, kdhttps requested changes
@sokorototo thanks for a initial code. It's looking good. It will good to add some test cases and `README.md` with setup, run test cases, and usage of library instructions.

2024-06-11 08:55 UTC, kdhttps commented on jans-lock/cedarling/src/utils.rs
> +pub async fn get_str(url: &str, _: &Tokens) -> Option<String> {
can we add unit test for get_str func?

2024-06-11 08:55 UTC, kdhttps commented on jans-lock/cedarling/src/utils.rs
> +pub async fn fetch_schema() -> cedar_policy::Schema {
it will be good to add a unit test for fetch_schema.

2024-06-11 08:55 UTC, kdhttps commented on jans-lock/cedarling/tests/fetch-schema.rs
> +	console_log!("Fetched Schema: {:?}", &schema)
Can we check the `let schema` with some values? Adding some `assert()` statements here will be good.

2024-06-11 08:55 UTC, kdhttps commented on jans-lock/cedarling/src/lib.rs
> +pub async fn init(auth: JsValue, entities: Option<String>, policies: Option<String>) {
is it possible to add an integration test for `lib.rs` functions?

2024-06-11 12:43 UTC, sokorototo commented on jans-lock/cedarling/src/utils.rs
> +pub async fn get_str(url: &str, _: &Tokens) -> Option<String> {
Will do!

2024-06-11 12:43 UTC, sokorototo commented on jans-lock/cedarling/tests/fetch-schema.rs
> +	console_log!("Fetched Schema: {:?}", &schema)
Oh it was a temporary test, just to make sure `utils::fetch_schema` was working. I will validate the data next!

2024-06-11 12:44 UTC, sokorototo commented on jans-lock/cedarling/src/lib.rs
> +pub async fn init(auth: JsValue, entities: Option<String>, policies: Option<String>) {
Yes, I can setup some unit tests for these.

2024-06-11 12:45 UTC, sokorototo commented
@kdhttps do you mind merging this currently, and then creating a new issue for the unit tests? Otherwise the commit might get larger

2024-06-12 02:03 UTC, kdhttps commented
> @kdhttps do you mind merging this currently, and then creating a new issue for the unit tests? Otherwise the commit might get larger

ageeed

2024-06-12 02:04 UTC, kdhttps approved these changes

2024-06-12 14:32 UTC, SafinWasi approved these changes
Looks good to me. Once we have a basic POC, can you add a README on how to compile and run this locally?

2024-06-12 16:28 UTC, sokorototo commented
> agreed

You can create a new issue, I am sure to follow up!

2024-06-14 10:32 UTC, yurem approved these changes

2024-06-14 10:32 UTC, merged