feat(charts)!: helm support for custom annotations and serviceAccount
JanssenProject/jans pull request #8910
Opened 2024-07-09 08:46 UTC by misba7

closes #8625 

This introduces breaking changes to the helm chart as it:

Changes the ingress annotations and labels location.
Introduces a separate Service account.
PLEASE BE ADVISED.

2024-07-09 08:53 UTC, mo-auto submitted a review, later dismissed

2024-07-10 09:02 UTC, moabu approved these changes

2024-08-06 18:27 UTC, iromli requested changes

2024-08-06 18:27 UTC, iromli commented on charts/janssen-all-in-one/values.yaml
> -    lockLabels: {}
The `lockLabels` and `lockAdditionalAnnotations` should be moved to appropriate location instead of deleting them.

2024-08-06 18:27 UTC, iromli commented on charts/janssen/charts/nginx-ingress/values.yaml
> -  lockLabels: { }
The `lockLabels` and `lockAdditionalAnnotations` should be moved to appropriate location instead of deleting them.

2024-08-06 18:27 UTC, iromli commented on charts/janssen/charts/nginx-ingress/README.md
> +<<<<<<< HEAD
Remove leftovers from conflict resolution.

2024-08-06 18:29 UTC, iromli commented
@misba7 Don't forget to re-run `helm-docs` to rebuild docs

2024-08-07 13:55 UTC, iromli approved these changes

2024-08-07 18:28 UTC, iromli approved these changes

2024-08-08 13:40 UTC, merged