fix(jans-setup): corrected jansscr
JanssenProject/jans pull request #9100
Opened 2024-08-02 17:20 UTC by shekhar16

https://github.com/JanssenProject/jans/issues/9087
Corrected JansScr as per @devrimyatar  suggestion.

2024-08-02 17:21 UTC, mo-auto commented
Error: Hi @shekhar16, You did not reference an open issue in your [PR](9100). I attempted to create an [issue](#9101) for you.    
 Please update that [issues'](#9101) title and body and make sure I correctly referenced it in the above PRs body.

2024-08-02 19:39 UTC, devrimyatar requested changes
All letters in placeholder `fido2_fido2extensionSample`bshould be lowercase

2024-08-03 06:35 UTC, devrimyatar approved these changes

2024-08-03 19:40 UTC, yuriyz approved these changes

2024-08-03 19:40 UTC, merged