fix(jans-fido2): #8901
JanssenProject/jans pull request #9120
Opened 2024-08-05 17:08 UTC by maduvena

Removing deprecated Formats

2024-09-05 07:05 UTC, yackermann commented on docs/admin/fido/config.md
> +| rp                                      | [{"id":"https://my-jans-server.jans.io","origins":["my-jans-server.jans.io"]}] | Requested party id.
id -> rpId, and it should be set to host "my-jans-server.jans.io"

origins need to be ["https://my-jans-server.jans.io"]

2024-09-05 07:13 UTC, yackermann requested changes

2024-09-05 07:13 UTC, yackermann commented on jans-fido2/model/src/main/java/io/jans/fido2/ctap/CoseEdDSAAlgorithm.java
> +public enum CoseEdDSAAlgorithm {
EDDSA can be dropped. FIDO never supported, and never will. If EDDSA is present then return error.

2024-09-05 07:13 UTC, yackermann commented on jans-fido2/model/src/main/java/io/jans/fido2/model/assertion/AssertionOptions.java
> +    public void setDocumentDomain(String documentDomain) {
what is documentDomain?

2024-09-05 07:13 UTC, yackermann commented on jans-fido2/model/src/main/java/io/jans/fido2/model/attestation/AttestationOptions.java
> +        return documentDomain;
Same. What is a document domain?

2024-09-05 07:13 UTC, yackermann commented on jans-fido2/model/src/main/java/io/jans/fido2/model/common/PublicKeyCredentialDescriptor.java
> +    private String[] transports;
Transports need typisation.

2024-09-05 07:13 UTC, yackermann commented on jans-fido2/server/src/main/java/io/jans/fido2/service/operation/AssertionService.java
> +		if (!Strings.isNullOrEmpty(assertionOptions.getSuperGluuAppId())) {
SuperGluu needs to be removed

2024-09-05 07:13 UTC, yackermann commented on jans-fido2/server/src/main/java/io/jans/fido2/service/operation/AttestationService.java
>  		if (!superGluu) {
SuperGluu needs to be nuked

2024-09-05 07:13 UTC, yackermann commented on jans-fido2/server/src/main/java/io/jans/fido2/service/sg/converter/AssertionSuperGluuController.java
> +        assertionOptions.setSuperGluuAppId(appId);
Super gluu nuuuuked

2024-09-18 16:06 UTC, maduvena commented on jans-fido2/model/src/main/java/io/jans/fido2/model/attestation/AttestationOptions.java
> +        return documentDomain;
Origin

2024-09-18 16:12 UTC, maduvena commented on jans-fido2/server/src/main/java/io/jans/fido2/service/operation/AttestationService.java
>  		if (!superGluu) {
Done in #9453

2024-09-18 16:13 UTC, maduvena commented on jans-fido2/server/src/main/java/io/jans/fido2/service/operation/AssertionService.java
> +		if (!Strings.isNullOrEmpty(assertionOptions.getSuperGluuAppId())) {
#9453 done

2024-09-18 16:14 UTC, maduvena commented on jans-fido2/model/src/main/java/io/jans/fido2/model/attestation/AttestationOptions.java
> +        return documentDomain;
changed in #8906

2024-09-25 07:03 UTC, yackermann commented
Thanks @imran-ishaq @moabu 

I will review changes tomorrow

2024-11-07 08:17 UTC, moabu commented
Closed in favor of a rebase here https://github.com/JanssenProject/jans/pull/10078

2024-11-07 08:17 UTC, closed without merging