feat(jans-cli-tui): acr screen
JanssenProject/jans pull request #9167
Opened 2024-08-12 10:27 UTC by devrimyatar

closes #8217

- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

2024-08-29 10:27 UTC, ossdhaval requested changes

2024-08-29 10:27 UTC, ossdhaval commented on docs/admin/config-guide/auth-server-config/default-authentication-method-config.md
@devrimyatar Since the contents of this file are no longer just focused on default ACR, I suggest we rename this file and remove the `default` word from it. And update the mkdocs.yaml and the heading in the file accordingly.

2024-08-29 10:27 UTC, ossdhaval commented on docs/admin/config-guide/auth-server-config/default-authentication-method-config.md
> +If you want to add a new alias, chose **Add Alias** button and hit **Enter**
I believe the screenshot is missing here.

2024-08-29 10:32 UTC, ossdhaval commented on docs/admin/config-guide/auth-server-config/default-authentication-method-config.md
@devrimyatar Are there any other commands that should be listed under CLI section?

2024-08-29 11:17 UTC, ossdhaval commented on docs/admin/config-guide/auth-server-config/default-authentication-method-config.md
Added commits to resolve this.

2024-08-30 03:59 UTC, ossdhaval approved these changes

2024-08-30 08:32 UTC, pujavs approved these changes

2024-08-30 08:37 UTC, devrimyatar commented on docs/admin/config-guide/auth-server-config/default-authentication-method-config.md
Not really. This is screen is just compalition of many CLI commands.

2024-08-30 08:37 UTC, devrimyatar commented on docs/admin/config-guide/auth-server-config/default-authentication-method-config.md
Thanks

2024-08-30 09:00 UTC, merged