docs: custom asset mgt documentation update for optional attribute
JanssenProject/jans pull request #9258
Opened 2024-08-23 15:53 UTC by pujavs

### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description
Issue#9257: Custom asset documentation update for optional atrribute

#### Target issue
  
  
  
  
closes #9257

#### Implementation Details
  

-------------------
### Test and Document the changes
- [ ] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [ ] **I confirm that there is no impact on the docs due to the code changes in this PR.**

2024-08-23 16:00 UTC, mo-auto submitted a review, later dismissed

2024-08-26 13:12 UTC, ossdhaval requested changes

2024-08-26 13:12 UTC, ossdhaval commented on docs/admin/config-guide/custom-assets-configuration.md
> +**Note:** `assetFile` attribute is optional for update operation as there may be scenario where only metadata of an asset is to be updated.
Add the comment using syntax as used [here](https://github.com/JanssenProject/jans/blob/74089549832425a100ad25ddd4aee5f223309c2e/docs/admin/auth-server/client-management/client-configuration.md?plain=1#L124). It'll render the comment as in [this](https://docs.jans.io/v1.1.4/admin/auth-server/client-management/client-configuration/#recommendations-for-using-grant-types-and-flows) section of the rendered documentation site.

2024-08-27 08:42 UTC, pujavs commented on docs/admin/config-guide/custom-assets-configuration.md
> +**Note:** `assetFile` attribute is optional for update operation as there may be scenario where only metadata of an asset is to be updated.
@ossdhaval, i have changed as per suggestion, request you to please review

2024-08-27 08:49 UTC, ossdhaval approved these changes

2024-08-27 09:58 UTC, devrimyatar approved these changes

2024-08-27 09:58 UTC, merged