feat(cedarling): add an example application using python binding
JanssenProject/jans pull request #9479
Opened 2024-09-12 14:03 UTC by olehbozhok

### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

#### Target issue
  [Link](https://github.com/JanssenProject/jans/issues/9434)
  
  
closes #9434

#### Implementation Details
  Added folder `bindings\example_cedarling_python_poetry`. With example of application using `poetry`

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [ ] Relevant unit and integration tests have been added/updated
- [x] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [ ] **I confirm that there is no impact on the docs due to the code changes in this PR.**

2024-09-12 15:12 UTC, SafinWasi requested changes
Code worked for me, but documentation needs fixing

2024-09-12 15:12 UTC, SafinWasi commented on jans-lock/cedarling/examples/cedarling_python_poetry/README.md
> +    Watch to the `cedarling_python` folder and in [README.md](../../bindings\cedarling_python\README.md) file.
This path is broken on Github. Please use unix path separator `/` for paths.
![image](https://github.com/user-attachments/assets/96d3df14-beb2-43b3-a91f-d629800083de)

2024-09-12 15:12 UTC, SafinWasi commented on jans-lock/cedarling/examples/cedarling_python_poetry/README.md
> +    Where `D:\upwork\jans\jans-lock\cedarling\target\wheels\cedarling_python-0.1.0-cp311-none-win_amd64.whl` is the path of the `whl` file.
Please use partial paths, absolute paths may not exist on other systems

2024-09-12 15:12 UTC, SafinWasi commented on jans-lock/cedarling/examples/cedarling_python_poetry/README.md
> +1. **Install Dependencies **
Syntax error for bold, should be `**Install Dependencies**`

2024-09-12 15:12 UTC, SafinWasi commented on jans-lock/cedarling/examples/cedarling_python_poetry/pythonpoetry.py
> +    req.access_token = input("insert assess_token:")
Typo, `assess_token` should be `access_token`

2024-09-12 15:12 UTC, SafinWasi commented on jans-lock/cedarling/examples/cedarling_python_poetry/README.md
> +    After executing the last command `maturin build` you will see in the console something like this:
Should be `maturin build --release`

2024-09-12 15:53 UTC, olehbozhok commented on jans-lock/cedarling/examples/cedarling_python_poetry/README.md
> +    Watch to the `cedarling_python` folder and in [README.md](../../bindings\cedarling_python\README.md) file.
resolved

2024-09-12 15:54 UTC, olehbozhok commented on jans-lock/cedarling/examples/cedarling_python_poetry/README.md
> +    After executing the last command `maturin build` you will see in the console something like this:
resolved

2024-09-12 15:54 UTC, olehbozhok commented on jans-lock/cedarling/examples/cedarling_python_poetry/README.md
> +    Where `D:\upwork\jans\jans-lock\cedarling\target\wheels\cedarling_python-0.1.0-cp311-none-win_amd64.whl` is the path of the `whl` file.
updated with prefix
`D:\path_to_the_project`

2024-09-12 15:54 UTC, olehbozhok commented on jans-lock/cedarling/examples/cedarling_python_poetry/README.md
> +1. **Install Dependencies **
resolved

2024-09-12 15:55 UTC, olehbozhok commented on jans-lock/cedarling/examples/cedarling_python_poetry/pythonpoetry.py
> +    req.access_token = input("insert assess_token:")
resolved

2024-09-12 16:02 UTC, SafinWasi approved these changes
Looks good

2024-09-13 03:53 UTC, moabu approved these changes

2024-09-13 03:53 UTC, merged