feat(config-api): client token mgt endpoint
JanssenProject/jans pull request #9554
Opened 2024-09-20 14:59 UTC by pujavs

### Prepare

- [ ] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ ] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

#### Target issue
  
  
  
  
closes #9413

#### Implementation Details
  

-------------------
### Test and Document the changes
- [] Static code analysis has been run locally and issues have been fixed
- [] Relevant unit and integration tests have been added/updated
- [ ] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [ ] **I confirm that there is no impact on the docs due to the code changes in this PR.**

2024-09-20 15:16 UTC, yuriyz requested changes
@pujavs I see /server/src/main/java/io/jans/configapi/rest/resource/auth/ClientsResource.java.bak

Do we need it ?

2024-09-20 15:23 UTC, pujavs commented
> @pujavs I see /server/src/main/java/io/jans/configapi/rest/resource/auth/ClientsResource.java.bak
> 
> Do we need it ?

Thanks for pointing this out, have removed it

2024-09-20 16:03 UTC, yuriyz approved these changes

2024-09-21 08:46 UTC, devrimyatar approved these changes

2024-09-21 08:46 UTC, merged