docs(docker-compose): update docs to be more comprehensive
JanssenProject/jans pull request #9658
Opened 2024-10-03 07:08 UTC by misba7

closes #9654

2024-10-04 19:45 UTC, iromli approved these changes

2024-10-08 06:38 UTC, moabu requested changes

2024-10-08 06:38 UTC, moabu commented on docker-jans-monolith/clean.sh
> -
why are you removing this ?

2024-10-08 09:00 UTC, misba7 commented on docker-jans-monolith/clean.sh
> -
It's a duplicate.

2024-10-08 11:40 UTC, moabu approved these changes

2024-10-08 11:40 UTC, merged