docs(user-mgt): restructure user management documentation
JanssenProject/jans pull request #9745
Opened 2024-10-15 07:31 UTC by imShakil

### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description

#### Target issue
  #9470 
  
 
  

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [x] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [x] **I confirm that there is no impact on the docs due to the code changes in this PR.**

2024-10-15 07:38 UTC, mo-auto approved these changes

2024-10-15 08:58 UTC, ossdhaval commented
@imShakil Please check the impact on below and fix if needed.
- navigation (mkdocs.yml)
- links from other documents to the changed documents in this PR

2024-10-15 16:09 UTC, imShakil commented
> @imShakil Please check the impact on below and fix if needed.
> 
> * navigation (mkdocs.yml)
> * links from other documents to the changed documents in this PR

These are okay.

2024-10-24 08:37 UTC, ossdhaval requested changes

2024-10-24 08:37 UTC, ossdhaval commented on docs/janssen-server/scim/config.md
> +1. Launch TUI, e.g. by running `python3 /opt/jans/jans-cli/jans_cli_tui.py`, and follow the prompts
To run TUI, we are now using `jans tui` wrapper command. So the document should use the same.

2024-10-24 08:37 UTC, ossdhaval commented on docs/janssen-server/scim/custom-attributes.md
> +* Navigate to `SCIM` using Jans TUI `/opt/jans/jans-cli/jans_cli_tui.py`
same as the previous comment, we should now be using new `jans` wrapper command. That is `jans tui`.

2024-10-24 09:10 UTC, imShakil commented
Thanks for the finding @ossdhaval  I have add commit regarding on those changes.

2024-10-24 09:11 UTC, ossdhaval approved these changes

2024-10-24 09:27 UTC, mzico approved these changes

2024-10-28 02:03 UTC, closed without merging