refactor(docs): refactor interception script documentation
JanssenProject/jans pull request #9753
Opened 2024-10-15 16:08 UTC by mmrraju

### Prepare

- [x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)

-------------------

### Description
Update:

This PR refactors script documentation by moving all files under docs/admin/developer/scripts to a new folder docs/script-catalog.

This change was made to:

- Improve clarity in locating script-related documentation.
- Create a more logical and centralized documentation structure.

#### Target issue
  
  https://github.com/JanssenProject/jans/issues/5924
  
  
closes #issue-number-here

#### Implementation Details
  

-------------------
### Test and Document the changes
- [x] Static code analysis has been run locally and issues have been fixed
- [x] Relevant unit and integration tests have been added/updated
- [x] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)

Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.
- [x] **I confirm that there is no impact on the docs due to the code changes in this PR.**

2024-10-15 16:10 UTC, mmrraju commented
I need to adjust the DCO; that's why I'm creating the PR again.

2024-10-15 16:22 UTC, mo-auto approved these changes

2024-10-15 16:31 UTC, mzico approved these changes

2024-10-15 16:42 UTC, mo-auto approved these changes

2024-10-16 08:40 UTC, ossdhaval requested changes

2024-10-16 08:40 UTC, ossdhaval commented on docs/janssen-server/developer/scripts/id-token.md
@mmrraju This and other files with placeholder content, actually serve as a placeholder where we plan to develop content. These are like TODOs. 
In such cases, we keep the files in the file system so that we can visit them later, but remove them from navigation (mkdocs.yml).

For the purpose of this PR, you may move them to place that is appropriate as per the new structure and remove them from navigation if there are part of it.

2024-10-16 16:03 UTC, mmrraju commented on docs/janssen-server/developer/scripts/id-token.md
@ossdhaval Please correct me if I'm wrong
1. The file like `docs/janssen-server/developer/scripts/id-token.md` we keep in same directory but remove from navigation. 
2. Besides which we already replaced to 'docs/script-catalog`, now we will add this to navigation(mkdocs.yml). 

right ?



![Screenshot from 2024-10-16 21-14-59](https://github.com/user-attachments/assets/8a458ee1-8028-4a74-abb8-6db29dbf574d)

2024-10-17 14:24 UTC, ossdhaval commented on docs/janssen-server/developer/scripts/id-token.md
1. Yes
2. Yes

2024-10-17 15:08 UTC, ossdhaval commented on docs/janssen-server/developer/scripts/id-token.md
Hi @mmrraju 

1. No. Move the `.md` file to under appropriate directory (create if it doesn't already exist) under `script-catalog`. This is true for all the `.md` files under `janssen-server/developer/scripts`. If the `.md` just have placeholder content then still make the move to `script-catalog` but it won't show up under navigation as mentioned in point below.
2. No. While all the files (`.md` as well as corresponding `.py`/`.java` files) are physically located under `script-catalog` the navigation would be from under the `developer guide` with path pointing to location under `script-catalog`. For example `Application Session: script-catalog/application-session/application-session.md`

2024-10-17 17:52 UTC, mmrraju commented on docs/janssen-server/developer/scripts/id-token.md
Thanks @ossdhaval , l'm doing...

2024-10-17 23:03 UTC, mmrraju commented on docs/janssen-server/developer/scripts/id-token.md
@ossdhaval  please check. I modified according to above discussion.

2024-10-18 09:07 UTC, ossdhaval requested changes

2024-10-18 09:07 UTC, ossdhaval commented on docs/script-catalog/README.md
@mmrraju This content should be moved to `developer/scripts/README.md` and then remove this file.

2024-10-18 15:05 UTC, mmrraju commented on docs/script-catalog/README.md
@ossdhaval , change request done. `script-catalog/README.md` file move to `/developer/scripts/README.md` and updated on `mkdocs.yml` file. check please.

2024-10-21 07:24 UTC, ossdhaval approved these changes

2024-10-21 08:21 UTC, merged